name: test

on:
  push:
    branches:
      [main, dev]
  pull_request:
    branches:
      [main, dev]
    
jobs:
  test:
    name: python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
         
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Update pip and install testing pkgs
        run: |
          python -VV
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Install package
        run: python -m pip install --no-deps .
      
      - name: Install dependencies via pip
        if: ${{ matrix.os }} == 'ubuntu-latest' or ${{ matrix.os }} == 'macos-latest'
        run: pip install -r requirements.txt
      
      - name: Set environment variables
        if: ${{ matrix.os }} == 'windows-latest'
        run: |
          echo "CONDA_ENV_FILE=environment.yml" >> $GITHUB_ENV
      
      - name: Use micromamba to install dependencies via conda for windows
        if: ${{ matrix.os }} == 'windows-latest'
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ env.CONDA_ENV_FILE }}
          micromamba-version: 'latest'
      
      - name: Run pytest
        run: pytest -v harmonize_wq
